all:
  children:
    manager-servers:
      hosts:
        rabbit-manager:
          ansible_host: 49.13.239.186   #change
          ansible_user: root
          ansible_port: 22
    
    worker-servers:
      hosts:
        rabbit-worker1:
          ansible_host: 49.13.239.172   #change 
          ansible_user: root
          ansible_port: 22

        rabbit-worker2:
          ansible_host: 49.12.239.199   #change
          ansible_user: root
          ansible_port: 22

    load-balancer-servers:
      hosts:
        haproxy-server:
          ansible_host: 159.69.45.233   #change 
          ansible_user: root
          ansible_port: 22  

