---
# tasks file for hardening
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Remove systemd-timesyncd if it conflicts with ntpsec
  apt:
    name: systemd-timesyncd
    state: absent

- name: Install basic tools
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes

- name: Set hostname
  hostname:
    name: '{{ inventory_hostname }}'

- name: Fix /etc/hosts
  template:
    src: "hosts.j2"
    dest: "/etc/hosts"
