# advertise ip addresses for docker swarm cluster 
ADVERTISE_ADDRESS: ip_address
ADVERTISE_ADDRESS_MANAGER2: ip_address
ADVERTISE_ADDRESS_MANAGER3: ip_address
ADVERTISE_ADDRESS_WORKER1: ip_address
ADVERTISE_ADDRESS_WORKER2: ip_address
ADVERTISE_ADDRESS_WORKER3: ip_address

# docker swarm networks
NETWORK1_NAME: "network1_name"
NETWORK1_BRIDGE_NAME: "network1_bridge_name"
NETWORK1_ENCRYPTED: 'no'

NETWORK2_NAME: "network2_name"
NETWORK2_BRIDGE_NAME: "network2_bridge_name"
NETWORK2_ENCRYPTED: 'no'

NETWORK3_NAME: "network3_name"
NETWORK3_BRIDGE_NAME: "network3_bridge_name"
NETWORK3_ENCRYPTED: 'yes'

# docker swarm secrets
SECRET1_NAME: secret1_name
SECRET1_DATA_SRC: /path/to/file/secret1

SECRET2_NAME: secret2_name
SECRET2_DATA_SRC: /path/to/file/secret2

SECRET3_NAME: secret3_name
SECRET3_DATA_SRC: /path/to/file/secret3
