- hosts: all
  vars:
    ansible_ssh_private_key_file: /Users/siavashmohseni/.ssh/id_rsa
  become: true
  gather_facts: true
  name: install docker
  roles:
    - { role: roles/docker, bcome: True, tags: docker_setup }
