- hosts: all
  vars:
    ansible_ssh_private_key_file: /Users/siavashmohseni/.ssh/id_rsa
  become: true
  serial: 1
  gather_facts: true
  name: Create docker swarm cluster
  tasks:
    - name: Initialize Swarm
      command: docker swarm init --advertise-addr {{ ADVERTISE_ADDRESS }}
      register: swarm_init_output
      changed_when: "'Swarm initialized' in swarm_init_output.stdout"
      when: ansible_hostname == 'rabbit-manager'

    - name: Get worker join token
      command: docker swarm join-token -q worker
      register: worker_join_token
      when: ansible_hostname == 'rabbit-manager'

    - name: Wait for token to be available
      pause:
        seconds: 5
      when: ansible_hostname != 'rabbit-manager'

    - name: Join rabbit worker1
      command: docker swarm join --token {{ hostvars['rabbit-manager']['worker_join_token'].stdout }} {{ ADVERTISE_ADDRESS }}:2377
      when:
        - ansible_hostname == 'rabbit-worker1'

    - name: Join rabbit worker2
      command: docker swarm join --token {{ hostvars['rabbit-manager']['worker_join_token'].stdout }} {{ ADVERTISE_ADDRESS }}:2377
      when:
        - ansible_hostname == 'rabbit-worker2'
