---
- hosts: all
  become: true
  gather_facts: true
  name: install and configure management server
  roles:
  # preparing server and hardening
    - { role: roles/preparing, become: True, tags: preparing }
