- hosts: all
  become: true
  serial: 1
  gather_facts: true
  name: install Docker SDK package
  tasks:
    - name: Ensure Docker SDK for Python is installed
      command: pip install docker --break-system-packages

    - name: Verify Docker SDK installation
      command: python3 -c "import docker; print(docker.__version__)"
      register: docker_sdk_version

    - name: Print Docker SDK version
      debug:
        msg: "Docker SDK version: {{ docker_sdk_version.stdout }}"
