- hosts: manager-server-1
  vars:
    ansible_ssh_private_key_file: /Users/siavashmohseni/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3
  become: true
  gather_facts: true
  name: Create networks in docker swarm cluster
  tasks:
    - name: Create docker swarm overlay networks
      community.docker.docker_network:
        name: "{{ item.name }}"
        driver: overlay
        attachable: yes
        driver_options:
          com.docker.network.bridge.name: "{{ item.bridge_name }}"
          encrypted: "{{ item.encrypted }}"
      loop: 
        - { name: "{{ NETWORK1_NAME }}", bridge_name: "{{ NETWORK1_BRIDGE_NAME }}", encrypted: "{{ NETWORK1_ENCRYPTED }}" }
        - { name: "{{ NETWORK2_NAME }}", bridge_name: "{{ NETWORK2_BRIDGE_NAME }}", encrypted: "{{ NETWORK2_ENCRYPTED }}" }
        - { name: "{{ NETWORK3_NAME }}", bridge_name: "{{ NETWORK3_BRIDGE_NAME }}", encrypted: "{{ NETWORK3_ENCRYPTED }}" }
      tags: create_networks

    - name: Read secrets from target node
      slurp:
        src: "{{ item }}"
      register: secret_contents
      loop: 
        - "{{ SECRET1_DATA_SRC }}"
        - "{{ SECRET2_DATA_SRC }}"
        - "{{ SECRET3_DATA_SRC }}"
      tags: create_secrets

    - name: Create Docker secrets
      community.docker.docker_secret:
        name: "{{ item.name }}"
        data: "{{ item.content }}"
      loop: 
        - name: "{{ SECRET1_NAME }}"
          content: "{{ secret_contents.results[0].content | b64decode }}"
        - name: "{{ SECRET2_NAME }}"
          content: "{{ SECRET2_DATA_SRC }}"
        - name: "{{ SECRET3_NAME }}"
          content: "{{ secret_contents.results[1].content | b64decode }}"
      register: secrets
      tags: create_secrets

    - name: Debug secret creation output
      debug:
        var: secrets
      tags: create_secrets

